# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rapon\PycharmProjects\boltcalc\boltui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bolt_ui(object):
    def setupUi(self, bolt_ui):
        bolt_ui.setObjectName("bolt_ui")
        bolt_ui.resize(766, 459)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bolt_ui.sizePolicy().hasHeightForWidth())
        bolt_ui.setSizePolicy(sizePolicy)
        bolt_ui.setSizeGripEnabled(True)
        bolt_ui.setModal(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(bolt_ui)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(bolt_ui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lengthText = QtWidgets.QLineEdit(self.tab)
        self.lengthText.setObjectName("lengthText")
        self.gridLayout.addWidget(self.lengthText, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 14, 0, 1, 2)
        self.partCombo = QtWidgets.QComboBox(self.tab)
        self.partCombo.setObjectName("partCombo")
        self.gridLayout.addWidget(self.partCombo, 15, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 15, 1, 1, 1)
        self.gradeCombo = QtWidgets.QComboBox(self.tab)
        self.gradeCombo.setObjectName("gradeCombo")
        self.gridLayout.addWidget(self.gradeCombo, 7, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 1, 1, 1)
        self.renutlineEdit = QtWidgets.QLineEdit(self.tab)
        self.renutlineEdit.setObjectName("renutlineEdit")
        self.gridLayout.addWidget(self.renutlineEdit, 18, 3, 1, 1)
        self.rmnutlineEdit = QtWidgets.QLineEdit(self.tab)
        self.rmnutlineEdit.setObjectName("rmnutlineEdit")
        self.gridLayout.addWidget(self.rmnutlineEdit, 19, 3, 1, 1)
        self.recnutlineEdit = QtWidgets.QLineEdit(self.tab)
        self.recnutlineEdit.setObjectName("recnutlineEdit")
        self.gridLayout.addWidget(self.recnutlineEdit, 20, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 18, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 19, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 20, 1, 1, 1)
        self.sizeCombo = QtWidgets.QComboBox(self.tab)
        self.sizeCombo.setObjectName("sizeCombo")
        self.gridLayout.addWidget(self.sizeCombo, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.gradeNutCombo = QtWidgets.QComboBox(self.tab)
        self.gradeNutCombo.setObjectName("gradeNutCombo")
        self.gridLayout.addWidget(self.gradeNutCombo, 17, 3, 1, 1)
        self.nutCombo = QtWidgets.QComboBox(self.tab)
        self.nutCombo.setObjectName("nutCombo")
        self.gridLayout.addWidget(self.nutCombo, 16, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 16, 1, 1, 1)
        self.typeCombo = QtWidgets.QComboBox(self.tab)
        self.typeCombo.setObjectName("typeCombo")
        self.gridLayout.addWidget(self.typeCombo, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.nClampedPartsText = QtWidgets.QLineEdit(self.tab)
        self.nClampedPartsText.setObjectName("nClampedPartsText")
        self.gridLayout.addWidget(self.nClampedPartsText, 0, 3, 1, 1)
        self.rmlineedit = QtWidgets.QLineEdit(self.tab)
        self.rmlineedit.setEnabled(True)
        self.rmlineedit.setReadOnly(True)
        self.rmlineedit.setObjectName("rmlineedit")
        self.gridLayout.addWidget(self.rmlineedit, 10, 3, 1, 1)
        self.reclineedit = QtWidgets.QLineEdit(self.tab)
        self.reclineedit.setEnabled(True)
        self.reclineedit.setReadOnly(True)
        self.reclineedit.setObjectName("reclineedit")
        self.gridLayout.addWidget(self.reclineedit, 11, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 1, 1, 1)
        self.relineedit = QtWidgets.QLineEdit(self.tab)
        self.relineedit.setEnabled(True)
        self.relineedit.setReadOnly(True)
        self.renutlineEdit.setReadOnly(True)
        self.rmnutlineEdit.setReadOnly(True)
        self.recnutlineEdit.setReadOnly(True)

        self.relineedit.setObjectName("relineedit")
        self.gridLayout.addWidget(self.relineedit, 9, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.scrollLayout = QtWidgets.QFormLayout()

        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setLayout(self.scrollLayout)

        self.scrollArea = QtWidgets.QScrollArea()
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setWidget(self.scrollWidget)

        self.mainLayout = QtWidgets.QVBoxLayout(self.tab_2)

        self.mainLayout.addWidget(self.scrollArea)

        self.retranslateUi(bolt_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bolt_ui)

    def retranslateUi(self, bolt_ui):
        _translate = QtCore.QCoreApplication.translate
        bolt_ui.setWindowTitle(_translate("bolt_ui", "Bolt Calculation UX"))
        self.label_3.setText(_translate("bolt_ui", "Length:"))
        self.label_7.setText(_translate("bolt_ui", "<html><head/><body><p><span style=\" font-weight:600;\">Threaded Part</span></p></body></html>"))
        self.label_10.setText(_translate("bolt_ui", "Grade:"))
        self.label_8.setText(_translate("bolt_ui", "Type of part:"))
        self.label_11.setText(_translate("bolt_ui", "Re:"))
        self.label_14.setText(_translate("bolt_ui", "Re:"))
        self.label_15.setText(_translate("bolt_ui", "Rm:"))
        self.label_16.setText(_translate("bolt_ui", "Rec:"))
        self.label_6.setText(_translate("bolt_ui", "Type:"))
        self.label.setText(_translate("bolt_ui", "<html><head/><body><p><span style=\" font-weight:600;\">Number of clamped parts:</span></p></body></html>"))
        self.label_5.setText(_translate("bolt_ui", "Size:"))
        self.label_9.setText(_translate("bolt_ui", "Type of nut:"))
        self.label_2.setText(_translate("bolt_ui", "<html><head/><body><p><span style=\" font-weight:600;\">Bolt</span></p></body></html>"))
        self.nClampedPartsText.setPlaceholderText(_translate("bolt_ui", "Enter values between 2-10"))
        self.label_12.setText(_translate("bolt_ui", "Rm:"))
        self.label_4.setText(_translate("bolt_ui", "Grade:"))
        self.label_13.setText(_translate("bolt_ui", "Rec:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("bolt_ui", "Inputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("bolt_ui", "Clamped Parts"))


